project:
  type: book

book:
  title: "Kenya Statistical Quality Assurance Framework (KeSQAF)"
  author: "Kenya National Bureau of Statistics"
  date: "2026-01-04"
  chapters:
    - index.qmd
    - quality-context-concepts.qmd
    - statistical-system.qmd
    - quality-assurance-principles.qmd
    - implementation.qmd
    - references.qmd
  search: true
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    pinned: true
    title: ""
  page-navigation: true

format:
  html:
    theme: cosmo
    css: knbs-style.css
    toc: true
    toc-location: right
    toc-depth: 4
    toc-title: "On This Page"
    number-sections: true
    number-depth: 4
    html-math-method: katex
    code-fold: false
    page-layout: full
