project:
  type: book

book:
  title: "Kenya Statistical Production Model"
  author: "Kenya National Bureau of Statistics"
  date: "2026-01-04"
  chapters:
    - index.md
    - part: "Introduction"
      chapters:
        - Introduction/About KNBS.md
        - Introduction/GSBPM.md
        - Introduction/Supporting Frameworks.md
    - part: "Process 1: Specify Needs"
      chapters:
        - Process1/1.md
        - Process1/1.1.md
        - Process1/1.2.md
        - Process1/1.3.md
        - Process1/1.4.md
        - Process1/1.5.md
        - Process1/1.6.md
    - part: "Process 2: Design"
      chapters:
        - Process2/2.md
        - Process2/2.1.md
        - Process2/2.2.md
        - Process2/2.3.md
        - Process2/2.4.md
        - Process2/2.5.md
        - Process2/2.6.md
    - part: "Process 3: Build"
      chapters:
        - Process3/3.md
        - Process3/3.1.md
        - Process3/3.2.md
        - Process3/3.3.md
        - Process3/3.4.md
        - Process3/3.5.md
        - Process3/3.6.md
        - Process3/3.7.md
    - part: "Process 4: Collect"
      chapters:
        - Process4/4.md
        - Process4/4.1.md
        - Process4/4.2.md
        - Process4/4.3.md
        - Process4/4.4.md
    - part: "Process 5: Process"
      chapters:
        - Process5/5.md
        - Process5/5.1.md
        - Process5/5.2.md
        - Process5/5.3.md
        - Process5/5.4.md
        - Process5/5.5.md
        - Process5/5.6.md
        - Process5/5.7.md
        - Process5/5.8.md
    - part: "Process 6: Analyse"
      chapters:
        - Process6/6.md
        - Process6/6.1.md
        - Process6/6.2.md
        - Process6/6.3.md
        - Process6/6.4.md
        - Process6/6.5.md
    - part: "Process 7: Disseminate"
      chapters:
        - Process7/7.md
        - Process7/7.1.md
        - Process7/7.2.md
        - Process7/7.3.md
        - Process7/7.4.md
        - Process7/7.5.md
    - part: "Process 8: Evaluate"
      chapters:
        - Process8/8.md
        - Process8/8.1.md
        - Process8/8.2.md
        - Process8/8.3.md
  search: true
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    pinned: true
  page-navigation: true

format:
  html:
    theme: cosmo
    css: knbs-style.css
    toc: true
    toc-location: right
    toc-depth: 4
    toc-title: "On This Page"
    number-sections: true
    number-depth: 4
    html-math-method: katex
    code-fold: false
    page-layout: full
