project:
  type: website

website:
  title: "Kenya Statistical Compendium"
  navbar:
    background: "#b06443"
    foreground: "white"
    left:
      - href: index.qmd
        text: "Home"
        icon: house
      - text: "Statistics"
        icon: bar-chart
        menu:
          - href: demographic-social-statistics.qmd
            text: "Demographic & Social"
            icon: people
          - href: economic-statistics.qmd
            text: "Economic"
            icon: currency-exchange
          - href: environment-statistics.qmd
            text: "Environment"
            icon: globe
          - href: governance-statistics.qmd
            text: "Governance"
            icon: shield-check
          - href: cross-cutting-statistics.qmd
            text: "Cross-cutting"
            icon: arrow-repeat
      - href: statistical-infrastructure.qmd
        text: "Infrastructure"
        icon: tools
      - href: strategic-activities-references.qmd
        text: "Strategic Activities"
        icon: clipboard-data
    search: true
  sidebar:
    style: "docked"
    location: right
    contents:
      - index.qmd
      - demographic-social-statistics.qmd
      - economic-statistics.qmd
      - environment-statistics.qmd
      - governance-statistics.qmd
      - cross-cutting-statistics.qmd
      - statistical-infrastructure.qmd
      - strategic-activities-references.qmd

format:
  html:
    theme: flatly
    toc: true
    toc-location: right
    toc-depth: 3
    number-sections: true
    css: styles.css
    smooth-scroll: false
    anchor-sections: false
